### ISSUE TITLE
CBF documentation

### ISSUE THREAD

**Issue by sonicpp** [sonicpp/VC-Browser#29]
Document all known about CBF file format.

**Comment by Romop5** [comment]
I tried to reverse CBF a little bit two years ago in https://github.com/Romop5/vietcong-unpacker/blob/master/cbf.txt I'd like to help you with this project. Please, contact me at rom.dobias@gmail.com or FB: Roman Dobias.

**Comment by sonicpp** [comment]
@Romop5 thank you. I used some info provided by your project in [vc-spec project](https://github.com/OpenVietcong/vc-spec) (and I also moved doc/scripts into that project). Closing
